# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobuf import media_analysis_pb2 as protobuf_dot_media__analysis__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/media_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaAnalysisServiceStub(object):
    """MediaAnalysisService provides various AI-powered analysis features for media content
    rpc AnalyzeAudio(AudioAnalysisRequest) returns (AudioAnalysisResponse);
    rpc AnalyzeVideo(VideoAnalysisRequest) returns (VideoAnalysisResponse);
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateTranscript = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/GenerateTranscript',
                request_serializer=protobuf_dot_media__analysis__pb2.TranscriptRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.TranscriptResponse.FromString,
                _registered_method=True)
        self.DetectKeyMoments = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/DetectKeyMoments',
                request_serializer=protobuf_dot_media__analysis__pb2.KeyMomentsRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.KeyMomentsResponse.FromString,
                _registered_method=True)
        self.AnalyzeTopics = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/AnalyzeTopics',
                request_serializer=protobuf_dot_media__analysis__pb2.TopicAnalysisRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.TopicAnalysisResponse.FromString,
                _registered_method=True)
        self.AnalyzeSentiment = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/AnalyzeSentiment',
                request_serializer=protobuf_dot_media__analysis__pb2.SentimentRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.SentimentResponse.FromString,
                _registered_method=True)
        self.GenerateChapters = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/GenerateChapters',
                request_serializer=protobuf_dot_media__analysis__pb2.ChapterRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.ChapterResponse.FromString,
                _registered_method=True)
        self.GenerateSummary = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/GenerateSummary',
                request_serializer=protobuf_dot_media__analysis__pb2.SummaryRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.GenerateShortForm = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/GenerateShortForm',
                request_serializer=protobuf_dot_media__analysis__pb2.ShortFormRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.ShortFormResponse.FromString,
                _registered_method=True)
        self.ExtractQuotes = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/ExtractQuotes',
                request_serializer=protobuf_dot_media__analysis__pb2.QuoteExtractionRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.QuoteExtractionResponse.FromString,
                _registered_method=True)
        self.GenerateMetadata = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/GenerateMetadata',
                request_serializer=protobuf_dot_media__analysis__pb2.MetadataRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.MetadataResponse.FromString,
                _registered_method=True)
        self.DetectSoundscape = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/DetectSoundscape',
                request_serializer=protobuf_dot_media__analysis__pb2.SoundscapeRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.SoundscapeResponse.FromString,
                _registered_method=True)
        self.AnalyzeEngagement = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/AnalyzeEngagement',
                request_serializer=protobuf_dot_media__analysis__pb2.EngagementRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.EngagementResponse.FromString,
                _registered_method=True)
        self.DetectFaceEmotions = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/DetectFaceEmotions',
                request_serializer=protobuf_dot_media__analysis__pb2.FaceEmotionRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.FaceEmotionResponse.FromString,
                _registered_method=True)
        self.GenerateContentWarnings = channel.unary_unary(
                '/media_analysis.MediaAnalysisService/GenerateContentWarnings',
                request_serializer=protobuf_dot_media__analysis__pb2.ContentWarningRequest.SerializeToString,
                response_deserializer=protobuf_dot_media__analysis__pb2.ContentWarningResponse.FromString,
                _registered_method=True)


class MediaAnalysisServiceServicer(object):
    """MediaAnalysisService provides various AI-powered analysis features for media content
    rpc AnalyzeAudio(AudioAnalysisRequest) returns (AudioAnalysisResponse);
    rpc AnalyzeVideo(VideoAnalysisRequest) returns (VideoAnalysisResponse);
    """

    def GenerateTranscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectKeyMoments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSentiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateChapters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateShortForm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractQuotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectSoundscape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeEngagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFaceEmotions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateContentWarnings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTranscript,
                    request_deserializer=protobuf_dot_media__analysis__pb2.TranscriptRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.TranscriptResponse.SerializeToString,
            ),
            'DetectKeyMoments': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectKeyMoments,
                    request_deserializer=protobuf_dot_media__analysis__pb2.KeyMomentsRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.KeyMomentsResponse.SerializeToString,
            ),
            'AnalyzeTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTopics,
                    request_deserializer=protobuf_dot_media__analysis__pb2.TopicAnalysisRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.TopicAnalysisResponse.SerializeToString,
            ),
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=protobuf_dot_media__analysis__pb2.SentimentRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.SentimentResponse.SerializeToString,
            ),
            'GenerateChapters': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateChapters,
                    request_deserializer=protobuf_dot_media__analysis__pb2.ChapterRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.ChapterResponse.SerializeToString,
            ),
            'GenerateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSummary,
                    request_deserializer=protobuf_dot_media__analysis__pb2.SummaryRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.SummaryResponse.SerializeToString,
            ),
            'GenerateShortForm': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateShortForm,
                    request_deserializer=protobuf_dot_media__analysis__pb2.ShortFormRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.ShortFormResponse.SerializeToString,
            ),
            'ExtractQuotes': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractQuotes,
                    request_deserializer=protobuf_dot_media__analysis__pb2.QuoteExtractionRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.QuoteExtractionResponse.SerializeToString,
            ),
            'GenerateMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateMetadata,
                    request_deserializer=protobuf_dot_media__analysis__pb2.MetadataRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.MetadataResponse.SerializeToString,
            ),
            'DetectSoundscape': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectSoundscape,
                    request_deserializer=protobuf_dot_media__analysis__pb2.SoundscapeRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.SoundscapeResponse.SerializeToString,
            ),
            'AnalyzeEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeEngagement,
                    request_deserializer=protobuf_dot_media__analysis__pb2.EngagementRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.EngagementResponse.SerializeToString,
            ),
            'DetectFaceEmotions': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFaceEmotions,
                    request_deserializer=protobuf_dot_media__analysis__pb2.FaceEmotionRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.FaceEmotionResponse.SerializeToString,
            ),
            'GenerateContentWarnings': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateContentWarnings,
                    request_deserializer=protobuf_dot_media__analysis__pb2.ContentWarningRequest.FromString,
                    response_serializer=protobuf_dot_media__analysis__pb2.ContentWarningResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'media_analysis.MediaAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('media_analysis.MediaAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaAnalysisService(object):
    """MediaAnalysisService provides various AI-powered analysis features for media content
    rpc AnalyzeAudio(AudioAnalysisRequest) returns (AudioAnalysisResponse);
    rpc AnalyzeVideo(VideoAnalysisRequest) returns (VideoAnalysisResponse);
    """

    @staticmethod
    def GenerateTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/GenerateTranscript',
            protobuf_dot_media__analysis__pb2.TranscriptRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.TranscriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectKeyMoments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/DetectKeyMoments',
            protobuf_dot_media__analysis__pb2.KeyMomentsRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.KeyMomentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/AnalyzeTopics',
            protobuf_dot_media__analysis__pb2.TopicAnalysisRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.TopicAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/AnalyzeSentiment',
            protobuf_dot_media__analysis__pb2.SentimentRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateChapters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/GenerateChapters',
            protobuf_dot_media__analysis__pb2.ChapterRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.ChapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/GenerateSummary',
            protobuf_dot_media__analysis__pb2.SummaryRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateShortForm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/GenerateShortForm',
            protobuf_dot_media__analysis__pb2.ShortFormRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.ShortFormResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractQuotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/ExtractQuotes',
            protobuf_dot_media__analysis__pb2.QuoteExtractionRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.QuoteExtractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/GenerateMetadata',
            protobuf_dot_media__analysis__pb2.MetadataRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectSoundscape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/DetectSoundscape',
            protobuf_dot_media__analysis__pb2.SoundscapeRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.SoundscapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/AnalyzeEngagement',
            protobuf_dot_media__analysis__pb2.EngagementRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.EngagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFaceEmotions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/DetectFaceEmotions',
            protobuf_dot_media__analysis__pb2.FaceEmotionRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.FaceEmotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateContentWarnings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_analysis.MediaAnalysisService/GenerateContentWarnings',
            protobuf_dot_media__analysis__pb2.ContentWarningRequest.SerializeToString,
            protobuf_dot_media__analysis__pb2.ContentWarningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
